# Generated by Django 3.2.5 on 2021-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_sub_catagories'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('offer_price', models.CharField(max_length=20)),
                ('final_price', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
