# Generated by Django 3.2.5 on 2021-07-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagories',
            old_name='Catagory_name',
            new_name='catagory',
        ),
    ]
