# Generated by Django 3.2.5 on 2021-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_rename_catagory_name_catagories_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
