# Generated by Django 3.2.5 on 2021-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_catagories_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_id', models.IntegerField()),
                ('Cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_Catagories',
        ),
    ]
