# Generated by Django 3.2.5 on 2021-07-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_auto_20210731_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='Cat_id',
        ),
    ]
