# Generated by Django 3.2.5 on 2021-08-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_catagory_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catgory', to='Myapp.catagory'),
            preserve_default=False,
        ),
    ]
