# Generated by Django 3.2.4 on 2021-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_alter_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='Cpassword',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
